# Generated by Django 3.2 on 2022-03-14 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo_ejercicio',
            field=models.CharField(choices=[('NOTVR', 'No VR'), ('VR', 'VR')], default='NOTVR', max_length=5),
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.ImageField(upload_to='')),
                ('administrador', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='centro',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vroom.centro'),
        ),
    ]
