# Generated by Django 3.2 on 2022-03-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terminos',
            new_name='Termino',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='terminos',
            new_name='termino',
        ),
    ]
