# Generated by Django 3.2 on 2022-03-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='terminos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vroom.terminos'),
        ),
    ]
