# Generated by Django 3.2 on 2022-04-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0002_auto_20220401_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='auto_puntuacion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vroom.auto_puntuacion'),
        ),
    ]
