# Generated by Django 3.2 on 2022-03-14 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0002_alter_usuario_terminos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(null=True)),
                ('autor', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vroom.curso')),
            ],
        ),
        migrations.AlterField(
            model_name='terminos',
            name='texto',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
