# Generated by Django 3.2 on 2022-03-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0002_auto_20220314_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercicio',
            old_name='tipo_ejercicio',
            new_name='tipo_ejercicios',
        ),
    ]
