# Generated by Django 3.2 on 2022-03-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0003_rename_tipo_ejercicio_ejercicio_tipo_ejercicios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercicio',
            old_name='tipo_ejercicios',
            new_name='tipo_ejercicio',
        ),
    ]
