# Generated by Django 3.2 on 2022-03-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0004_rename_tipo_ejercicios_ejercicio_tipo_ejercicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='tipo_ejercicio',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('NOTVR', 'NOTVR'), ('VR', 'VR')], default='NOTVR', max_length=6),
        ),
    ]
