# Generated by Django 3.2 on 2022-03-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0005_auto_20220314_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo_ejercicio',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vroom.tipo_ejercicio'),
        ),
    ]
